// Package skill renders the SKILL.md that teaches AI agents how to operate
// doktunnel.
//
// The document is built at runtime from a Spec that the CLI derives from its
// command tree and flag sets, and from the stable error codes in clierr, so it
// always describes the binary that prints it.
package skill

import (
	"fmt"
	"io"
	"strings"

	"github.com/alebak/dokploy-tunnel/internal/clierr"
)

// Spec describes the CLI surface documented by the skill.
type Spec struct {
	// Name is the binary name, also used as the skill name.
	Name string
	// Summary is a one-line description of what the binary does.
	Summary string
	// Commands lists every command below the root, depth first.
	Commands []Command
	// GlobalFlags are accepted by every command.
	GlobalFlags []Flag
	// RootFlags are accepted only by the root command.
	RootFlags []Flag
}

// Command is one command of the tree.
type Command struct {
	// Path is the full invocation, such as "doktunnel context".
	Path string
	// Summary is the one-line description.
	Summary string
	// Description is optional longer help text.
	Description string
	// Args names the positional arguments, such as "<name>"; it may be empty.
	Args string
	// Flags are the command's own flags, in addition to the global ones.
	Flags []Flag
}

// Flag is one command-line flag.
type Flag struct {
	// Name is the flag name without dashes.
	Name string
	// Arg names the flag's value; it is empty for boolean flags.
	Arg string
	// Usage describes the flag.
	Usage string
}

// description tells an agent when to load the skill. It is quoted in the
// frontmatter because it contains ": ".
const description = "Operate the doktunnel CLI, which forwards Dokploy services to stable local hostnames and ports. " +
	"Trigger: when a task needs to reach a service deployed on Dokploy from this machine, " +
	"manage doktunnel contexts, forwards or local hostname entries, or interpret doktunnel errors and exit codes."

// meanings explains each stable error code in the error table. A test fails
// when a code in clierr has no entry here.
var meanings = map[clierr.Code]string{
	clierr.Internal:             "Unexpected failure",
	clierr.InvalidArgument:      "Unknown or malformed command, flag, or argument",
	clierr.MissingInput:         "A required value is missing and prompting is not allowed",
	clierr.NotImplemented:       "The command exists but is not implemented yet",
	clierr.PermissionDenied:     "The caller lacks permission for the operation",
	clierr.NetworkNotAttachable: "The target network cannot be attached",
	clierr.ElevationRequired:    "The operation needs administrator privileges",
	clierr.Unreachable:          "A remote endpoint could not be reached",
}

// Write renders the SKILL.md for s to w.
func Write(w io.Writer, s Spec) error {
	var b strings.Builder
	writeFrontmatter(&b, s)
	writeIntro(&b, s)
	writeCommands(&b, s)
	writeFlags(&b, s)
	writeOutput(&b, s)
	writeErrors(&b)
	writeWorkflows(&b, s)
	if _, err := io.WriteString(w, b.String()); err != nil {
		return fmt.Errorf("writing skill: %w", err)
	}
	return nil
}

func writeFrontmatter(b *strings.Builder, s Spec) {
	fmt.Fprintf(b, "---\nname: %s\ndescription: %q\n---\n\n", s.Name, description)
}

func writeIntro(b *strings.Builder, s Spec) {
	fmt.Fprintf(b, "# %s\n\n", s.Name)
	if s.Summary != "" {
		fmt.Fprintf(b, "%s\n\n", s.Summary)
	}
	fmt.Fprintf(b, "This skill was generated by `%s --skill` from the installed binary, "+
		"so it matches that binary's commands, flags, and error codes. "+
		"Regenerate it after upgrading %s.\n\n", s.Name, s.Name)
}

func writeCommands(b *strings.Builder, s Spec) {
	b.WriteString("## Commands\n\n")
	b.WriteString("| Command | Purpose |\n|---------|---------|\n")
	for _, c := range s.Commands {
		fmt.Fprintf(b, "| `%s` | %s |\n", c.Path, cell(c.Summary))
	}
	fmt.Fprintf(b, "\nRun `%s <command> --help` for the usage of a command.\n\n", s.Name)
	for _, c := range s.Commands {
		if c.Description == "" && c.Args == "" && len(c.Flags) == 0 {
			continue
		}
		fmt.Fprintf(b, "### `%s`\n\n", c.Path)
		if c.Args != "" || len(c.Flags) > 0 {
			usage := c.Path + " [flags]"
			if c.Args != "" {
				usage += " " + c.Args
			}
			fmt.Fprintf(b, "Usage: `%s`\n\n", usage)
		}
		if c.Description != "" {
			fmt.Fprintf(b, "%s\n\n", c.Description)
		}
		if len(c.Flags) > 0 {
			writeFlagTable(b, c.Flags)
		}
	}
}

func writeFlags(b *strings.Builder, s Spec) {
	b.WriteString("## Global flags\n\n")
	b.WriteString("Every command accepts these flags, before or after its arguments:\n\n")
	writeFlagTable(b, s.GlobalFlags)
	if len(s.RootFlags) > 0 {
		fmt.Fprintf(b, "`%s` itself, without a command, also accepts:\n\n", s.Name)
		writeFlagTable(b, s.RootFlags)
	}
}

func writeFlagTable(b *strings.Builder, flags []Flag) {
	b.WriteString("| Flag | Purpose |\n|------|---------|\n")
	for _, f := range flags {
		name := "--" + f.Name
		if f.Arg != "" {
			name += " <" + f.Arg + ">"
		}
		fmt.Fprintf(b, "| `%s` | %s |\n", name, cell(f.Usage))
	}
	b.WriteString("\n")
}

func writeOutput(b *strings.Builder, s Spec) {
	b.WriteString("## Output conventions\n\n")
	b.WriteString("- With `--json`, results and errors are written to **stdout** as JSON and nothing is written to stderr. " +
		"Parse stdout and use the exit code to tell a result from an error.\n")
	b.WriteString("- A JSON error is a single object: `{\"code\":\"...\",\"message\":\"...\",\"hint\":\"...\"}`. " +
		"`hint` is omitted when empty.\n")
	fmt.Fprintf(b, "- Without `--json`, results go to stdout and errors go to stderr as `%s: <message> [<code>]`, "+
		"followed by a `hint:` line when there is one.\n", s.Name)
	b.WriteString("- Branch on the error `code` or the exit code, never on the message text. " +
		"Codes never change meaning; new codes may be added.\n\n")
}

func writeErrors(b *strings.Builder) {
	b.WriteString("## Error codes\n\n")
	b.WriteString("| Exit code | Error code | Meaning |\n|-----------|------------|---------|\n")
	b.WriteString("| 0 | — | Success |\n")
	for _, code := range clierr.Codes() {
		fmt.Fprintf(b, "| %d | `%s` | %s |\n", code.ExitCode(), code, cell(meanings[code]))
	}
	b.WriteString("\n")
}

func writeWorkflows(b *strings.Builder, s Spec) {
	b.WriteString("## Safe agent workflows\n\n")
	fmt.Fprintf(b, "1. Always pass `--json --no-input`, for example `%s status --json --no-input`. "+
		"Never rely on interactive prompts.\n", s.Name)
	fmt.Fprintf(b, "2. Run `%s status --json --no-input` before starting a forward, "+
		"and reuse an existing forward instead of starting a duplicate.\n", s.Name)
	b.WriteString("3. Pass `--context <name>` only when the human names a context; otherwise the current context is used.\n")
	fmt.Fprintf(b, "4. On `%s`, ask the human for the missing value named in `message` and `hint`, "+
		"then rerun with that flag. Never invent values.\n", clierr.MissingInput)
	fmt.Fprintf(b, "5. On `%s`, do not retry and do not elevate privileges yourself. "+
		"Tell the human which command needs administrator privileges and let them run it.\n", clierr.ElevationRequired)
	fmt.Fprintf(b, "6. On `%s`, read `%s <command> --help` and fix the invocation before trying again.\n",
		clierr.InvalidArgument, s.Name)
	fmt.Fprintf(b, "7. On `%s`, stop: this version cannot do it yet.\n", clierr.NotImplemented)
	b.WriteString("8. On any other error, report the code, message, and hint to the human instead of retrying in a loop.\n")
}

// cell escapes text for use inside a Markdown table cell.
func cell(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}
